In [16]:
import pandas as pd
import requests
pd.set_option('display.max_columns',None) # to see all columns in a wide dataframe
import time
import numpy as np

In [17]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2023-24&SeasonType=Playoffs&StatCategory=PTS'

In [18]:
r = requests.get(url=test_url).json()

In [19]:
table_headers = r['resultSet']['headers']

In [20]:
table_headers

['PLAYER_ID',
 'RANK',
 'PLAYER',
 'TEAM_ID',
 'TEAM',
 'GP',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'EFF',
 'AST_TOV',
 'STL_TOV']

In [21]:
pd.DataFrame(r['resultSet']['rowSet'], columns= table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Doncic,1610612742,DAL,22,899,225,504,0.446,68,211,0.322,117,153,0.765,16,192,208,178,41,8,90,56,635,665,1.98,0.46
1,202681,2,Kyrie Irving,1610612742,DAL,22,879,186,398,0.467,53,136,0.390,62,73,0.849,22,59,81,113,23,7,51,62,487,437,2.22,0.45
2,1628369,3,Jayson Tatum,1610612738,BOS,19,768,159,372,0.427,39,138,0.283,118,137,0.861,17,167,184,119,20,13,50,54,475,529,2.38,0.40
3,1627759,4,Jaylen Brown,1610612738,BOS,19,707,175,339,0.516,36,110,0.327,68,103,0.660,22,91,113,62,23,12,51,51,454,414,1.22,0.45
4,1630162,5,Anthony Edwards,1610612750,MIN,16,649,156,324,0.481,46,115,0.400,83,102,0.814,18,94,112,104,24,9,52,37,441,451,2.00,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00

In [22]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns= table_headers)
temp_df2 = pd.DataFrame({'Year':['2023-24' for i in range(len(temp_df1))],
'Season_type':['Playoffs' for i in range(len(temp_df1))]})

#temp_df2

temp_df3 = pd.concat([temp_df2,temp_df1],axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2023-24,Playoffs,1629029,1,Luka Doncic,1610612742,DAL,22,899,225,504,0.446,68,211,0.322,117,153,0.765,16,192,208,178,41,8,90,56,635,665,1.98,0.46
1,2023-24,Playoffs,202681,2,Kyrie Irving,1610612742,DAL,22,879,186,398,0.467,53,136,0.390,62,73,0.849,22,59,81,113,23,7,51,62,487,437,2.22,0.45
2,2023-24,Playoffs,1628369,3,Jayson Tatum,1610612738,BOS,19,768,159,372,0.427,39,138,0.283,118,137,0.861,17,167,184,119,20,13,50,54,475,529,2.38,0.40
3,2023-24,Playoffs,1627759,4,Jaylen Brown,1610612738,BOS,19,707,175,339,0.516,36,110,0.327,68,103,0.660,22,91,113,62,23,12,51,51,454,414,1.22,0.45
4,2023-24,Playoffs,1630162,5,Anthony Edwards,1610612750,MIN,16,649,156,324,0.481,46,115,0.400,83,102,0.814,18,94,112,104,24,9,52,37,441,451,2.00,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2023-24,Playoffs,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.000,0,0,0.000,0,0,0.000,0,3,3,1,0,0,0,0,0,2,0.00,0.00
210,2023-24,Playoffs,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.000,0,1,0.000,0,0,0.000,0,1,1,1,0,0,0,0,0,1,0.00,0.00
211,2023-24,Playoffs,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.000,0,1,0.000,0,0,0.000,2,1,3,1,0,0,0,0,0,2,0.00,0.00
212,2023-24,Playoffs,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2023-24,Playoffs,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,1,1,0,1,0,2,0.00,0.00

In [23]:
del temp_df1,temp_df2, temp_df3 #avoid overriding info

In [24]:
df_cols = ['Year','Season_type'] + table_headers

In [25]:
pd.DataFrame(columns =df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [26]:
headers = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'ttps://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': "Windows",
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
      
}  #maybe to make sure its not a bot?!

In [ ]:
df = pd.DataFrame(columns =df_cols)
season_types = ['Regular%20Season','Playoffs']
years = ['2012-13','2013-14','2014-15','2015-16',
         '2016-17','2017-18','2018-19','2019-20',
         '2020-21','2021-22','2022-23', '2023-24']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns= table_headers)
        temp_df2 = pd.DataFrame({'Year':[ y for i in range(len(temp_df1))],
        'Season_type':[ s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2,temp_df1],axis=1)
        df = pd.concat([df,temp_df3],axis=0)
        print(f'Finished Scarping data for the {y} {s}.')
        lag = np.random.uniform(low=5,high=40) #make it less botty
        print(f'....{round(lag,1)} seconds')
        time.sleep(lag) #inputting a lag
        
        
print(f'Process Completed! Total Run Time: {round((time.time()-begin_loop)/60,2)}')
df.to_excel('NBA_Player_Data_retest.xlsx', index=False)

Finished Scarping data for the 2012-13 Regular%20Season.
....14.1 seconds
Finished Scarping data for the 2012-13 Playoffs.
....21.8 seconds
Finished Scarping data for the 2013-14 Regular%20Season.
....11.6 seconds
Finished Scarping data for the 2013-14 Playoffs.
....30.7 seconds
Finished Scarping data for the 2014-15 Regular%20Season.
....10.4 seconds
Finished Scarping data for the 2014-15 Playoffs.
....10.0 seconds
Finished Scarping data for the 2015-16 Regular%20Season.
....20.7 seconds
Finished Scarping data for the 2015-16 Playoffs.
....37.2 seconds
Finished Scarping data for the 2016-17 Regular%20Season.
....6.8 seconds
Finished Scarping data for the 2016-17 Playoffs.
....23.4 seconds
Finished Scarping data for the 2017-18 Regular%20Season.
....34.4 seconds
Finished Scarping data for the 2017-18 Playoffs.
....36.7 seconds
Finished Scarping data for the 2018-19 Regular%20Season.
....21.2 seconds
Finished Scarping data for the 2018-19 Playoffs.
....36.0 seconds
Finished Scarping data for the 2019-20 Regular%20Season.
....9.6 seconds
Finished Scarping data for the 2019-20 Playoffs.
....30.3 seconds
Finished Scarping data for the 2020-21 Regular%20Season.
....29.4 seconds
Finished Scarping data for the 2020-21 Playoffs.
....28.4 seconds
Finished Scarping data for the 2021-22 Regular%20Season.
....9.5 seconds
Finished Scarping data for the 2021-22 Playoffs.
....9.6 seconds
Finished Scarping data for the 2022-23 Regular%20Season.
....39.5 seconds
Finished Scarping data for the 2022-23 Playoffs.
....36.6 seconds
Finished Scarping data for the 2023-24 Regular%20Season.
....20.5 seconds
Finished Scarping data for the 2023-24 Playoffs.
....38.8 seconds
Process Completed! Total Run Time: 9.78

In [ ]:
df